# ~/.config/hypr/bindings.conf
$mainMod = SUPER
$altMod = ALT

# --- Application Launchers ---
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, D, exec, $menu

# --- Window Management ---
bind = $mainMod SHIFT, C, exec, bash $HOME/.local/bin/kill_active # Kill active window
bind = $mainMod SHIFT, V, togglefloating,                         # Toggle floating
bind = $mainMod, P, pseudo,                                       # Pseudotile
bind = $mainMod, I, togglesplit,                                  # Toggle split

# --- Focus ---
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# --- Workspace Navigation ---
bind = $altMod, 1, workspace, 1
bind = $altMod, 2, workspace, 2
bind = $altMod, 3, workspace, 3
bind = $altMod, 4, workspace, 4
bind = $altMod, 5, workspace, 5
bind = $altMod, 6, workspace, 6
bind = $altMod, 7, workspace, 7
bind = $altMod, 8, workspace, 8
bind = $altMod, 9, workspace, 9
bind = $altMod, 0, workspace, 10

# --- Move Windows to Workspace ---
bind = $altMod SHIFT, 1, movetoworkspace, 1
bind = $altMod SHIFT, 2, movetoworkspace, 2
bind = $altMod SHIFT, 3, movetoworkspace, 3
bind = $altMod SHIFT, 4, movetoworkspace, 4
bind = $altMod SHIFT, 5, movetoworkspace, 5
bind = $altMod SHIFT, 6, movetoworkspace, 6
bind = $altMod SHIFT, 7, movetoworkspace, 7
bind = $altMod SHIFT, 8, movetoworkspace, 8
bind = $altMod SHIFT, 9, movetoworkspace, 9
bind = $altMod SHIFT, 0, movetoworkspace, 10

# --- Special Workspace ---
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# --- Mouse and Scroll ---
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# --- Media and Hardware Keys ---
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous