# Starship Configuration - Minimal Design with Catppuccin Macchiato Theme
# Optimized for development work with JetBrains Mono Nerd Font

# Simple format - no powerline
format = """
$time\
$custom_os_local\
$custom_os_ssh\
$directory\
$git_branch\
$git_status\
$golang\
$python\
$zig\
$nodejs\
$rust\
$docker_context\
$container\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# Color palette - Catppuccin Macchiato
palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

# OS with SSH detection (local)
[custom.os_local]
command = '''
case "$(uname)" in
  Darwin) echo "󰀵" ;;
  Linux) echo "󰌽" ;;
  *) echo "?" ;;
esac
'''
style = "bold blue"
when = """ test ! "$SSH_CLIENT" """
format = "[$output ]($style)"

# OS with SSH detection (SSH)
[custom.os_ssh]
command = '''
case "$(uname)" in
  Darwin) echo "󰀵" ;;
  Linux) echo "󰌽" ;;
  *) echo "?" ;;
esac
'''
style = "bold peach"
when = """ test "$SSH_CLIENT" """
format = "[$output ]($style)"

# Username
[username]
show_always = true
style_user = "bold green"
style_root = "bold red"
format = '[$user]($style)[@](subtext1)'

# Directory
[directory]
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

# Git branch
[git_branch]
symbol = ""
style = "bold mauve"
format = '[$symbol $branch]($style)'

# Git status
[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style)) '

# Language modules - minimal
[golang]
symbol = "󰟓"
style = "teal"
format = '[$symbol]($style) '
detect_files = ["go.mod", "go.sum", "*.go"]

[python]
symbol = ""
style = "yellow"
format = '[$symbol]($style) '
detect_files = ["requirements.txt", "pyproject.toml", "*.py"]

[zig]
symbol = ""
style = "orange"
format = '[$symbol]($style) '

[nodejs]
symbol = ""
style = "green"
format = '[$symbol]($style) '
detect_files = ["package.json", "*.js", "*.ts"]

[rust]
symbol = ""
style = "red"
format = '[$symbol]($style) '
detect_files = ["Cargo.toml", "*.rs"]

# Container runtime - minimal
[docker_context]
symbol = "󰡨"
style = "blue"
format = '[$symbol]($style) '
only_with_files = true

[container]
symbol = "⬢"
style = "blue"
format = '[$symbol]($style) '

# Time - simple
[time]
disabled = false
time_format = "%H:%M"
style = "subtext1"
format = '[⏱ $time]($style) '

# Line break and character
[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'
vimcmd_replace_one_symbol = '[❮](bold mauve)'
vimcmd_replace_symbol = '[❮](bold mauve)'
vimcmd_visual_symbol = '[❮](bold yellow)'

# Additional useful modules - minimal style
[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold yellow"
format = "[took $duration]($style) "

[jobs]
symbol = "✦"
style = "bold red"
number_threshold = 1
format = "[$symbol$number]($style) "

[hostname]
ssh_only = true
format = "[$hostname]($style):"
style = "bold blue"
disabled = false

# Disable the default OS module since we use custom
[os]
disabled = true
