theme = "catppuccin_macchiato"

[editor]
shell = ["zsh", "-c"]
line-number = "relative"
text-width = 100
continue-comments = false
auto-format = true
idle-timeout = 400
preview-completion-insert = true
completion-replace = false
true-color = true
undercurl = true
color-modes = true
bufferline = "multiple"
trim-trailing-whitespace = true
popup-border = "popup"
end-of-line-diagnostics = "hint"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-base-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
display-progress-messages = true
display-color-swatches = true
display-signature-help-docs = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
max-depth = 25

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.auto-save]
focus-lost = true

[editor.whitespace]
characters = { nbsp = "⍽", tab = "→" }

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
max-indent-retain = 0

[editor.inline-diagnostics]
cursor-line = "warning"
